### ISSUE TITLE
Unclear error message when getting credentials for a cluster.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [isusanin/google-cloud-sdk#648]
```
Issue running command [gcloud container clusters get].

What steps will reproduce the problem?
- gloud config set project prod-co
- gcloud container clusters get-credentials cluster-1

What is the expected output? What do you see instead?
Seeing as I have read-only access to this project, I have a strong suspicion 
this is what is causing the problem. However, the error message simply shows a 
generic Python exception being raised.

Please provide any additional information below.


Traceback (most recent call last):
  File "calliope/cli.py", line 609, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "calliope/backend.py", line 1228, in Run
    resources = command_instance.Run(args)
  File "surface/container/clusters/get_credentials.py", line 53, in Run
    util.ClusterConfig.Persist(cluster, cluster_ref.projectId, self.cli)
  File "api_lib/container/util.py", line 271, in Persist
    if auth.clientCertificate and auth.clientKey and auth.clusterCaCertificate:
AttributeError: 'NoneType' object has no attribute 'clientCertificate'

Installation information:

Google Cloud SDK [0.9.89]

Platform: [Linux, x86_64]
Python Version: [2.7.6 (default, Jun 22 2015, 17:58:13)  [GCC 4.8.2]]
Python Location: [/usr/bin/python2]
Site Packages: [Enabled]

Installation Root: [/home/ilia/code/google-cloud-sdk]
Installed Components:
  kubectl: []
  core-nix: [2015.11.24]
  core: [2015.11.30]
  gcloud: []
  gsutil-nix: [4.15]
  gsutil: [4.16]
  bq: [2.0.18]
  kubectl-linux-x86_64: [1.1.2]
  bq-nix: [2.0.18]
System PATH: 
[/home/ilia/Envs/flock-ldap-dev/bin:/home/ilia/code/google-cloud-sdk/bin:/usr/lo
cal/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/game
s]
Cloud SDK on PATH: [True]

Installation Properties: [/home/ilia/code/google-cloud-sdk/properties]
User Config Directory: [/home/ilia/.config/gcloud]
User Properties: [/home/ilia/.config/gcloud/properties]
Current Workspace: [None]
Workspace Config Directory: [None]
Workspace Properties: [None]

Account: [ilia.kurenkov@egym.de]
Project: [prod-co]

Current Properties:
  [core]
    project: [prod-co]
    account: [ilia.kurenkov@egym.de]
    disable_usage_reporting: [False]
  [app]
    suppress_change_warning: [true]
  [compute]
    zone: [europe-west1-d]

Logs Directory: [/home/ilia/.config/gcloud/logs]
Last Log File: [/home/ilia/.config/gcloud/logs/2016.03.14/13.10.08.353730.log]

```

Original issue reported on code.google.com by `ilia.kur...@egym.de` on 14 Mar 2016 at 12:16
- Merged into: #506

**Comment by GoogleCodeExporter** [comment]
```
Your version of the Cloud SDK is a couple of months out of date–do you still 
experience this with the latest version?
```

Original comment by `z...@google.com` on 14 Mar 2016 at 1:20
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
Original comment by `z...@google.com` on 14 Mar 2016 at 1:21
- Changed state: **Duplicate**
