### ISSUE TITLE
not able to run gcloud init 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [isusanin/google-cloud-sdk#649]
```
Issue running command [gcloud init].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "lib\googlecloudsdk\gcloud_main.py", line 169, in main
    gcloud_cli.Execute()
  File "lib\googlecloudsdk\calliope\cli.py", line 652, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "lib\googlecloudsdk\calliope\backend.py", line 1394, in Run
    resources = command_instance.Run(args)
  File "lib\googlecloudsdk\surface\init.py", line 106, in Run
    self.cli.Execute(['config', 'list'])
  File "lib\googlecloudsdk\calliope\cli.py", line 627, in Execute
    args = self.__parser.parse_args(args)
  File "lib\googlecloudsdk\calliope\backend.py", line 92, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "lib\googlecloudsdk\calliope\backend.py", line 83, in parse_known_args
    args, argv = super(ArgumentParser, self).parse_known_args(args, namespace)
  File "bin\..\lib\third_party\argparse\__init__.py", line 1735, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "bin\..\lib\third_party\argparse\__init__.py", line 1944, in _parse_known_args
    stop_index = consume_positionals(start_index)
  File "bin\..\lib\third_party\argparse\__init__.py", line 1900, in consume_positionals
    take_action(action, args)
  File "bin\..\lib\third_party\argparse\__init__.py", line 1809, in take_action
    action(self, namespace, argument_values, option_string)
[output truncated]

```

Original issue reported on code.google.com by `saji.geo...@sabercloud.com` on 14 Mar 2016 at 8:41

**Comment by GoogleCodeExporter** [comment]
```
Thanks for the feedback.

To help us investigate this further please post:

- Complete stack trace
- Complete output of gcloud info

Note: Redact any personal information before posting.

```

Original comment by `gsfow...@google.com` on 15 Mar 2016 at 1:36
- Changed state: **NeedsMoreInfo**
