### ISSUE TITLE
gcloud crashed with SSL CERT VERIFICATION

### ISSUE THREAD

**Issue by GoogleCodeExporter** [isusanin/google-cloud-sdk#650]
```
Issue running command [gcloud compute ssh].

What steps will reproduce the problem?

gcloud compute ssh [vm instance]

this error is intermittent. Not sure why it goes away eventually.

What is the expected output? What do you see instead?

connect to the instance

Please provide any additional information below.


Traceback (most recent call last):
  File "googlecloudsdk/gcloud_main.py", line 169, in main
    gcloud_cli.Execute()
  [...]
  File "googlecloudsdk/third_party/apitools/base/py/http_wrapper.py", line 340, in MakeRequest
    check_response_func=check_response_func)
  File "googlecloudsdk/third_party/apitools/base/py/http_wrapper.py", line 389, in _MakeRequestNoRetry
    redirections=redirections, connection_type=connection_type)
  File "googlecloudsdk/core/cli.py", line 330, in RequestWithErrHandling
    return orig_request(*args, **kwargs)
  File "third_party/oauth2client/client.py", line 569, in new_request
    redirections, connection_type)
  File "googlecloudsdk/core/cli.py", line 298, in RequestWithUserAgentAndTracing
    return orig_request(*modified_args, **kwargs)
  File "third_party/httplib2/__init__.py", line 1610, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "third_party/httplib2/__init__.py", line 1352, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "third_party/httplib2/__init__.py", line 1272, in _conn_request
    conn.connect()
  File "third_party/httplib2/__init__.py", line 1059, in connect
    raise SSLHandshakeError(e)
SSLHandshakeError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed 
(_ssl.c:590)

[output truncated]

```

Original issue reported on code.google.com by `noel.d.m...@macys.com` on 14 Mar 2016 at 9:41

**Comment by GoogleCodeExporter** [comment]
```
Thanks for the feedback.

This may be a problem with your Python installation. What version is installed?
```

Original comment by `gsfow...@google.com` on 15 Mar 2016 at 1:41
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
Python 2.7.11
```

Original comment by `noel.d.m...@macys.com` on 15 Mar 2016 at 5:16
